version: "3.8"
services:
  app:
    build:
      context: ./front-end
      dockerfile: Dockerfile
      target: dev
    ports:
      - 3000:3000
    volumes:
      - ./front-end:/react-app
      - /react-app/node_modules
    container_name: front-end

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./backend:/usr/src/app
      - /app/node_modules
    container_name: backend-container
